steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/Carbon-Hero:carbon-hero', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - ['auth', 'configure-docker']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'grc.io/$PROJECT_ID/Carbon-Hero:carbon-hero']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
    - 'c'
    - |
        PROJECT_ID=$(gcloud config get-value project)
        gcloud projects add-iam-policy-binding $PROJECT_ID \
          --member=serviceAccount:$PROJECT_ID@cloudbuild.gserviceaccount.com \
          --role=roles/run.admin
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
    - 'c'
    - |
      PROJECT_ID=$(gcloud config get-value project)
      gcloud projects add-iam-policy-binding $PROJECT_ID \
        --member=serviceAccount:$PROJECT_ID@cloudbuild.gserviceaccount.com \
        --role=roles/iam.serviceAccountUser

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
    - 'run'
    - 'deploy'
    - 'Carbon-Hero'
    - '--image'
    - 'grc.io/$PROJECT_ID/Carbon-Hero'
    - '--port'
    - '3000'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'