steps:
  - id: 'init'
    name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'echo NEXT_PUBLIC_API_KEY=$_NEXT_PUBLIC_API_KEY\\nNEXT_PUBLIC_AUTH_DOMAIN=$_NEXT_PUBLIC_AUTH_DOMAIN\\nNEXT_PUBLIC_PROJECT_ID=$_NEXT_PUBLIC_PROJECT_ID\\nNEXT_PUBLIC_STORAGE_BUCKET=$_NEXT_PUBLIC_STORAGE_BUCKET\\nNEXT_PUBLIC_SENDER_ID=$_NEXT_PUBLIC_SENDER_ID\\nNEXT_PUBLIC_APP_ID=$_NEXT_PUBLIC_APP_ID\\nNEXT_PUBLIC_MEASUREMENT_ID=$_NEXT_PUBLIC_MEASUREMENT_ID > .env']
    waitFor: ['-']

  - id: 'init2'
    name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'echo NEXT_PUBLIC_API_KEY=$_NEXT_PUBLIC_API_KEY\\nNEXT_PUBLIC_AUTH_DOMAIN=$_NEXT_PUBLIC_AUTH_DOMAIN\\nNEXT_PUBLIC_PROJECT_ID=$_NEXT_PUBLIC_PROJECT_ID\\nNEXT_PUBLIC_STORAGE_BUCKET=$_NEXT_PUBLIC_STORAGE_BUCKET\\nNEXT_PUBLIC_SENDER_ID=$_NEXT_PUBLIC_SENDER_ID\\nNEXT_PUBLIC_APP_ID=$_NEXT_PUBLIC_APP_ID\\nNEXT_PUBLIC_MEASUREMENT_ID=$_NEXT_PUBLIC_MEASUREMENT_ID > .env.production']
    waitFor: ['-']

  - id: build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/local-carbon-dev-deploy:$COMMIT_SHA', '.']
    env:
    - 'NEXT_PUBLIC_API_KEY=${_NEXT_PUBLIC_API_KEY}'
    - 'NEXT_PUBLIC_AUTH_DOMAIN=${_NEXT_PUBLIC_AUTH_DOMAIN}'
    - 'NEXT_PUBLIC_PROJECT_ID=${_NEXT_PUBLIC_PROJECT_ID}'
    - 'NEXT_PUBLIC_STORAGE_BUCKET=${_NEXT_PUBLIC_STORAGE_BUCKET}'
    - 'NEXT_PUBLIC_SENDER_ID=${_NEXT_PUBLIC_SENDER_ID}'
    - 'NEXT_PUBLIC_APP_ID=${_NEXT_PUBLIC_APP_ID}'
    - 'NEXT_PUBLIC_MEASUREMENT_ID=${_NEXT_PUBLIC_MEASUREMENT_ID}'

  - id: push
    waitFor: ['build']
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'grc.io/$PROJECT_ID/local-carbon-dev-deploy:$COMMIT_SHA']

  - id: deploy
    waitFor: ['push']
    name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'local-carbon-dev-deploy'
    - '--image'
    - 'gcr.io/$PROJECT_ID/local-carbon-dev-deploy:$COMMIT_SHA'
    - '--port'
    - '3000'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/local-carbon-dev-deploy:$COMMIT_SHA'